# Generated by Django 4.0.4 on 2022-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0002_orderitem_cake_flavor_orderitem_filling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
