# Generated by Django 4.0.4 on 2022-12-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeoption',
            name='serves',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AddField(
            model_name='cakeoption',
            name='size',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
