# Generated by Django 4.0.4 on 2022-12-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_options', '0002_cakeoption_serves_cakeoption_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakeoption',
            name='size',
        ),
    ]
