# Generated by Django 4.0.4 on 2022-12-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adjusted_price',
            field=models.IntegerField(default=0),
        ),
    ]
