# Generated by Django 4.0.4 on 2022-12-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_adjusted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_work_time',
            field=models.FloatField(),
        ),
    ]
