# Generated by Django 4.0.4 on 2022-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_total_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adjusted_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
