# Generated by Django 4.0.4 on 2023-01-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_adjusted_price_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='none', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='none', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(default='none', max_length=120),
            preserve_default=False,
        ),
    ]
