# Generated by Django 4.0.4 on 2022-12-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('work_time', models.FloatField()),
                ('serves', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
    ]
