# Generated by Django 4.0.4 on 2022-12-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serves',
        ),
    ]
