# Generated by Django 4.0.4 on 2022-12-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_serves'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricebydozen',
            field=models.BooleanField(default=False),
        ),
    ]
